# Generated by Django 5.1 on 2024-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KindleBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("sold_by", models.CharField(max_length=255)),
                ("img_url", models.URLField(max_length=500)),
                ("product_url", models.URLField(max_length=500)),
                ("stars", models.FloatField()),
                ("reviews", models.IntegerField()),
                ("price", models.FloatField()),
                ("is_kindle_unlimited", models.BooleanField()),
                ("category_id", models.IntegerField()),
                ("is_best_seller", models.BooleanField()),
                ("is_editors_pick", models.BooleanField()),
                ("is_good_reads_choice", models.BooleanField()),
                ("published_date", models.DateField()),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
    ]
