# Generated by Django 5.1 on 2024-08-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kindle", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kindlebook",
            name="reviews",
        ),
    ]
