# Generated by Django 5.1 on 2024-08-13 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(default='default.pdf', upload_to='book_pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='book_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_in',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Adventure', max_length=500),
            preserve_default=False,
        ),
    ]
