# Generated by Django 5.1 on 2024-08-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_genre_remove_book_pdf_book_book_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
